import type {
  Activity,
  Booking,
  Category,
  ChartPoint,
  Customer,
  Dispute,
  NotificationItem,
  Payment,
  Provider,
  Review,
  SupportTicket,
} from '@/types';

export const DASHBOARD_STATS = {
  totalUsers: 12840,
  totalProviders: 1862,
  verifiedProviders: 1540,
  pendingVerification: 47,
  todayBookings: 284,
  revenue: 486200,
};

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'u1',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    phone: '+91 98765 43210',
    bookings: 12,
    status: 'active',
    joinedAt: '2025-11-02',
  },
  {
    id: 'u2',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+91 91234 56789',
    bookings: 8,
    status: 'active',
    joinedAt: '2025-12-15',
  },
  {
    id: 'u3',
    name: 'Amit Verma',
    email: 'amit@example.com',
    phone: '+91 99887 76655',
    bookings: 3,
    status: 'suspended',
    joinedAt: '2026-01-20',
  },
  {
    id: 'u4',
    name: 'Neha Reddy',
    email: 'neha@example.com',
    phone: '+91 87654 32109',
    bookings: 21,
    status: 'active',
    joinedAt: '2025-09-08',
  },
  {
    id: 'u5',
    name: 'Karan Singh',
    email: 'karan@example.com',
    phone: '+91 90123 45678',
    bookings: 5,
    status: 'inactive',
    joinedAt: '2026-02-28',
  },
];

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: 'p1',
    name: 'Rajesh Kumar',
    email: 'rajesh@servicehub.com',
    phone: '+91 98765 43210',
    avatar: 'https://i.pravatar.cc/150?u=rajesh',
    category: 'Plumber',
    verificationStatus: 'pending',
    submittedAt: '2026-07-01',
    isOnline: true,
    rating: 4.9,
    jobsCompleted: 520,
    revenue: 342500,
    status: 'active',
    address: 'HSR Layout, Bengaluru',
    experience: '8 years',
    skills: ['Pipe Repair', 'Leak Fix'],
    certificates: ['Licensed Plumber'],
    documents: {
      aadhaar: 'https://i.pravatar.cc/400?u=aadhaar1',
      pan: 'https://i.pravatar.cc/400?u=pan1',
      selfie: 'https://i.pravatar.cc/400?u=selfie1',
      policeVerification: 'pending',
      bankDetails: 'HDFC ****4521',
    },
  },
  {
    id: 'p2',
    name: 'Suresh Patel',
    email: 'suresh@servicehub.com',
    phone: '+91 91234 56789',
    avatar: 'https://i.pravatar.cc/150?u=suresh',
    category: 'Electrician',
    verificationStatus: 'verified',
    submittedAt: '2026-06-15',
    isOnline: false,
    rating: 4.8,
    jobsCompleted: 410,
    revenue: 298000,
    status: 'active',
    address: 'Koramangala, Bengaluru',
    experience: '6 years',
    skills: ['Wiring', 'MCB Repair'],
    certificates: ['Electrical License'],
    documents: {
      aadhaar: 'https://i.pravatar.cc/400?u=aadhaar2',
      pan: 'https://i.pravatar.cc/400?u=pan2',
      selfie: 'https://i.pravatar.cc/400?u=selfie2',
      policeVerification: 'verified',
      bankDetails: 'ICICI ****8832',
    },
  },
  {
    id: 'p3',
    name: 'Meera Sharma',
    email: 'meera@servicehub.com',
    phone: '+91 99887 76655',
    avatar: 'https://i.pravatar.cc/150?u=meera',
    category: 'Home Cleaner',
    verificationStatus: 'rejected',
    submittedAt: '2026-06-28',
    isOnline: true,
    rating: 4.7,
    jobsCompleted: 680,
    revenue: 412000,
    status: 'active',
    address: 'Indiranagar, Bengaluru',
    experience: '5 years',
    skills: ['Deep Clean'],
    certificates: ['Hygiene Certified'],
    documents: {
      aadhaar: 'https://i.pravatar.cc/400?u=aadhaar3',
      pan: 'https://i.pravatar.cc/400?u=pan3',
      selfie: 'https://i.pravatar.cc/400?u=selfie3',
      policeVerification: 'pending',
      bankDetails: 'SBI ****2210',
    },
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'BK-2024-1847',
    customer: 'Alex Johnson',
    customerId: 'u1',
    provider: 'Rajesh Kumar',
    providerId: 'p1',
    service: 'Pipe Leak Fix',
    amount: 499,
    status: 'confirmed',
    paymentStatus: 'paid',
    date: '2026-07-05',
    location: 'Koramangala, Bengaluru',
    otp: '4829',
    timeline: [
      { label: 'Booking created', time: '10:00 AM', done: true },
      { label: 'Provider accepted', time: '10:15 AM', done: true },
      { label: 'Service started', time: '2:30 PM', done: false },
      { label: 'Completed', time: '-', done: false },
    ],
  },
  {
    id: 'BK-2024-1848',
    customer: 'Priya Sharma',
    customerId: 'u2',
    provider: 'Suresh Patel',
    providerId: 'p2',
    service: 'Switch Repair',
    amount: 349,
    status: 'in_progress',
    paymentStatus: 'paid',
    date: '2026-07-05',
    location: 'HSR Layout, Bengaluru',
    otp: '7153',
    timeline: [
      { label: 'Booking created', time: '9:00 AM', done: true },
      { label: 'Provider accepted', time: '9:10 AM', done: true },
      { label: 'Service started', time: '11:00 AM', done: true },
      { label: 'Completed', time: '-', done: false },
    ],
  },
  {
    id: 'BK-2024-1840',
    customer: 'Neha Reddy',
    customerId: 'u4',
    provider: 'Rajesh Kumar',
    providerId: 'p1',
    service: 'Tap Repair',
    amount: 299,
    status: 'completed',
    paymentStatus: 'paid',
    date: '2026-07-04',
    location: 'BTM Layout, Bengaluru',
    otp: '9031',
    timeline: [
      { label: 'Booking created', time: '3:00 PM', done: true },
      { label: 'Provider accepted', time: '3:05 PM', done: true },
      { label: 'Service started', time: '4:00 PM', done: true },
      { label: 'Completed', time: '4:45 PM', done: true },
    ],
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay1',
    bookingId: 'BK-2024-1840',
    customer: 'Neha Reddy',
    provider: 'Rajesh Kumar',
    amount: 299,
    commission: 30,
    status: 'paid',
    date: '2026-07-04',
  },
  {
    id: 'pay2',
    bookingId: 'BK-2024-1838',
    customer: 'Amit Verma',
    provider: 'Suresh Patel',
    amount: 599,
    commission: 60,
    status: 'pending',
    date: '2026-07-03',
  },
  {
    id: 'pay3',
    bookingId: 'BK-2024-1835',
    customer: 'Karan Singh',
    provider: 'Rajesh Kumar',
    amount: 2499,
    commission: 250,
    status: 'paid',
    date: '2026-07-02',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    rating: 5,
    customer: 'Priya S.',
    provider: 'Rajesh Kumar',
    review: 'Fixed the leak quickly and professionally.',
    reportCount: 0,
    status: 'visible',
    date: '2026-07-02',
  },
  {
    id: 'r2',
    rating: 2,
    customer: 'Amit K.',
    provider: 'Meera Sharma',
    review: 'Service was delayed significantly.',
    reportCount: 3,
    status: 'flagged',
    date: '2026-07-01',
  },
  {
    id: 'r3',
    rating: 4,
    customer: 'Neha R.',
    provider: 'Suresh Patel',
    review: 'Good work overall.',
    reportCount: 0,
    status: 'visible',
    date: '2026-06-30',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'c1',
    name: 'Plumber',
    description: 'Pipe repair, leak fixes, bathroom installations',
    icon: 'MdPlumbing',
    status: 'active',
  },
  {
    id: 'c2',
    name: 'Electrician',
    description: 'Wiring, switchboard repair, appliance electrical',
    icon: 'MdElectricalServices',
    status: 'active',
  },
  {
    id: 'c3',
    name: 'Home Cleaner',
    description: 'Deep cleaning for apartments and villas',
    icon: 'MdCleaningServices',
    status: 'active',
  },
  {
    id: 'c4',
    name: 'AC Repair',
    description: 'AC service, gas refill, installation',
    icon: 'MdAcUnit',
    status: 'inactive',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    title: 'Monsoon service offers',
    type: 'announcement',
    audience: 'All users',
    scheduledAt: '2026-07-10',
    status: 'scheduled',
  },
  {
    id: 'n2',
    title: 'New provider onboarding',
    type: 'push',
    audience: 'Providers',
    scheduledAt: '2026-07-06',
    status: 'sent',
  },
  {
    id: 'n3',
    title: 'Payment reminder',
    type: 'email',
    audience: 'Customers',
    scheduledAt: '-',
    status: 'draft',
  },
];

export const MOCK_DISPUTES: Dispute[] = [
  {
    id: 'D-101',
    bookingId: 'BK-2024-1830',
    customer: 'Amit Verma',
    provider: 'Meera Sharma',
    reason: 'Incomplete cleaning',
    status: 'open',
    createdAt: '2026-07-03',
  },
  {
    id: 'D-102',
    bookingId: 'BK-2024-1825',
    customer: 'Karan Singh',
    provider: 'Rajesh Kumar',
    reason: 'Overcharged for materials',
    status: 'investigating',
    createdAt: '2026-07-01',
  },
];

export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: 'T-501',
    user: 'Alex Johnson',
    category: 'Booking',
    priority: 'high',
    status: 'open',
    assignedAdmin: 'Sarah Admin',
    createdAt: '2026-07-05',
  },
  {
    id: 'T-502',
    user: 'Rajesh Kumar',
    category: 'Payment',
    priority: 'medium',
    status: 'in_progress',
    assignedAdmin: 'John Admin',
    createdAt: '2026-07-04',
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    message: 'New provider registration: Vikram Singh',
    time: '5 min ago',
    type: 'provider',
  },
  { id: 'a2', message: 'Booking BK-2024-1847 confirmed', time: '12 min ago', type: 'booking' },
  { id: 'a3', message: 'Payment of ₹499 received', time: '1 hr ago', type: 'payment' },
  { id: 'a4', message: 'New customer signup: Sneha Iyer', time: '2 hrs ago', type: 'user' },
];

export const REVENUE_CHART: ChartPoint[] = [
  { label: 'Jan', value: 320000 },
  { label: 'Feb', value: 380000 },
  { label: 'Mar', value: 410000 },
  { label: 'Apr', value: 390000 },
  { label: 'May', value: 450000 },
  { label: 'Jun', value: 486200 },
];

export const BOOKING_TREND: ChartPoint[] = [
  { label: 'Mon', value: 210 },
  { label: 'Tue', value: 245 },
  { label: 'Wed', value: 198 },
  { label: 'Thu', value: 284 },
  { label: 'Fri', value: 312 },
  { label: 'Sat', value: 356 },
  { label: 'Sun', value: 268 },
];

export const getProviderById = (id: string) => MOCK_PROVIDERS.find((p) => p.id === id);
export const getBookingById = (id: string) => MOCK_BOOKINGS.find((b) => b.id === id);
