import { MOCK_PROVIDERS } from '@/constants/customer/mockData';
import { DEFAULT_CUSTOMER_ID } from '@/constants/provider/accounts';
import type { Booking } from '@/types/customer';

const CUSTOMER = {
  id: DEFAULT_CUSTOMER_ID,
  name: 'Alex Johnson',
  phone: '+91 98765 43210',
  avatar: 'https://i.pravatar.cc/150?u=alex-customer',
};

function providerMeta(providerId: string) {
  const p = MOCK_PROVIDERS.find((x) => x.id === providerId);
  return {
    providerName: p?.name ?? 'Provider',
    categoryId: p?.categoryId ?? 'general',
  };
}

export function createSeedBookings(): Booking[] {
  const now = new Date().toISOString();

  return [
    {
      id: 'BK-1024',
      customerId: CUSTOMER.id,
      customerName: CUSTOMER.name,
      customerPhone: CUSTOMER.phone,
      customerAvatar: CUSTOMER.avatar,
      providerId: 'p1',
      ...providerMeta('p1'),
      service: 'Pipe Leak Fix',
      date: 'Jul 8, 2026',
      time: '10:30 AM',
      status: 'upcoming',
      providerStatus: 'accepted',
      price: 499,
      address: '42, 5th Block, Koramangala',
      otp: '4829',
      estimatedArrival: '15 min',
      createdAt: now,
    },
    {
      id: 'BK-1023',
      customerId: CUSTOMER.id,
      customerName: CUSTOMER.name,
      customerPhone: CUSTOMER.phone,
      customerAvatar: CUSTOMER.avatar,
      providerId: 'p4',
      ...providerMeta('p4'),
      service: 'AC Service',
      date: 'Jul 5, 2026',
      time: '2:00 PM',
      status: 'ongoing',
      providerStatus: 'accepted',
      price: 599,
      address: '42, 5th Block, Koramangala',
      otp: '7391',
      estimatedArrival: '8 min',
      createdAt: now,
    },
    {
      id: 'BK-1020',
      customerId: CUSTOMER.id,
      customerName: CUSTOMER.name,
      customerPhone: CUSTOMER.phone,
      customerAvatar: CUSTOMER.avatar,
      providerId: 'p3',
      ...providerMeta('p3'),
      service: '2 BHK Deep Clean',
      date: 'Jun 28, 2026',
      time: '9:00 AM',
      status: 'completed',
      providerStatus: 'accepted',
      price: 2199,
      address: '42, 5th Block, Koramangala',
      createdAt: now,
    },
    {
      id: 'BK-1018',
      customerId: CUSTOMER.id,
      customerName: CUSTOMER.name,
      customerPhone: CUSTOMER.phone,
      customerAvatar: CUSTOMER.avatar,
      providerId: 'p2',
      ...providerMeta('p2'),
      service: 'Switch Repair',
      date: 'Jun 20, 2026',
      time: '4:30 PM',
      status: 'cancelled',
      providerStatus: 'rejected',
      price: 349,
      address: '42, 5th Block, Koramangala',
      createdAt: now,
    },
    {
      id: 'BK-PENDING-P1',
      customerId: 'cust-2',
      customerName: 'Priya Sharma',
      customerPhone: '+91 99887 76655',
      customerAvatar: 'https://i.pravatar.cc/150?u=priya-customer',
      providerId: 'p1',
      ...providerMeta('p1'),
      service: 'Tap Repair',
      date: 'Jul 10, 2026',
      time: '4:00 PM',
      status: 'upcoming',
      providerStatus: 'pending',
      price: 299,
      address: '18, 12th Main, HSR Layout, Bengaluru',
      otp: '7153',
      createdAt: now,
    },
    {
      id: 'BK-PENDING-P5',
      customerId: 'cust-3',
      customerName: 'Sneha Iyer',
      customerPhone: '+91 91234 56780',
      customerAvatar: 'https://i.pravatar.cc/150?u=sneha-customer',
      providerId: 'p5',
      ...providerMeta('p5'),
      service: 'Haircut & Styling',
      date: 'Jul 11, 2026',
      time: '11:00 AM',
      status: 'upcoming',
      providerStatus: 'pending',
      price: 399,
      address: '25, 4th Cross, Indiranagar, Bengaluru',
      otp: '2846',
      createdAt: now,
    },
    {
      id: 'BK-PENDING-P2',
      customerId: 'cust-4',
      customerName: 'Amit Verma',
      customerPhone: '+91 87654 32109',
      customerAvatar: 'https://i.pravatar.cc/150?u=amit-customer',
      providerId: 'p2',
      ...providerMeta('p2'),
      service: 'Switch Repair',
      date: 'Jul 12, 2026',
      time: '3:30 PM',
      status: 'upcoming',
      providerStatus: 'pending',
      price: 349,
      address: '7, MG Road, Indiranagar, Bengaluru',
      otp: '9031',
      createdAt: now,
    },
  ];
}
